pipeline:
  name: malyadri-ci-golang-2
  identifier: malyadricigolang2
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: malyadrigolang
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: build
                  identifier: build
                  spec:
                    connectorRef: Malyadridocker
                    image: golang:tip
                    shell: Sh
                    command: |-
                      cd hello
                      go build
                      go test ./...
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      export SONAR_SCANNER_VERSION=6.2.0.4584
                      export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
                      curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
                      unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
                      export PATH=$SONAR_SCANNER_HOME/bin:$PATH

                      sonar-scanner \
                        -Dsonar.projectKey=golang-poc \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://mydomain2.mooo.com/sonarqube
                    envVariables:
                      SONAR_TOKEN: <+secrets.getValue("vault_password")>
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Malyadridocker
                    repo: malyadr/golang-poc
                    tags:
                      - latest
